version: '2'
services:
   rsyslog:
       image: fabriziogaliano/docker-rsyslog
      
       container_name: rsyslog-local-forward
 
       volumes:
          - "./etc/rsyslog.conf:/etc/rsyslog.conf"
          - "./rsyslog.d:/etc/rsyslog.d"
          - "./logs:/var/log"
          - "./certs-tls:/etc/certs-tls"
          - "./spool:/var/spool/rsyslog"

       ports:
          - "514:514/udp"

       restart: always
